spring:
  output.ansi.enabled: ALWAYS

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

colini.attach:
  file:
    uploadType: S3
    defaultUploadPath: temp/uploads
  aws:
    accessKey: ACCESS_KEY
    secretKey: SECRET_KEY
    region: ap-northeast-2
    s3:
      disable: true
      bucketName: colini