spring:
  output.ansi.enabled: ALWAYS

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet.multipart:
    enabled: true
    max-file-size: 50MB
    max-request-size: 100MB

colini.attach:
  file:
    uploadType: Local
    defaultUploadPath: temp/uploads
    limitUploadFileLength: 5
  aws:
    accessKey: ACCESS_KEY
    secretKey: SECRET_KEY
    region: ap-northeast-2
    s3:
      disable: true
      bucketName: colini