spring:
  output.ansi.enabled: ALWAYS
  data-source:
    url: jdbc:mysql://localhost:3306/attach?useUnicode=true&characterEncoding=UTF-8&useLocalSessionState=true
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server.port: 8080


colini.attach:
  file:
    uploadType: Local
    defaultUploadPath: temp/uploads
  aws:
    accessKey: ACCESS_KEY
    secretKey: SECRET_KEY
    region: ap-northeast-2
    s3:
      disable: true
      bucketName: colini